---
compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-kvm
  platform: linux
  cpu: 4
  memory: 16G
  disk: 100
  nested_virtualization: true

victoria_task:
  skip: "!changesInclude('.cirrus.yml', 'scripts/**')"

  environment:
    VERSION: victoria

  install_script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip install -r requirements.txt
    - bash scripts/install.sh

  submodules_script:
    - git submodule init
    - git submodule update

  build_script:
    - bash scripts/build.sh

  deploy_task:
    only_if: $CIRRUS_BRANCH == 'main'
    script: bash scripts/push.sh

wallaby_task:
  skip: "!changesInclude('.cirrus.yml', 'scripts/**')"

  environment:
    VERSION: wallaby

  install_script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip install -r requirements.txt
    - bash scripts/install.sh

  submodules_script:
    - git submodule init
    - git submodule update

  build_script:
    - bash scripts/build.sh

  deploy_task:
    only_if: $CIRRUS_BRANCH == 'main'
    script: bash scripts/push.sh
